### ISSUE TITLE
Install of v1.00_01 on Windows failed

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu#218]
Env: Windows 7 32-bit, Strawberry Perl v5.18.2

Error:

```terminal
t/Catmandu-Importer-YAML.t ............... ok

#   Failed test at t/Catmandu-Importer.t line 70.
#          got: 'http://demo.org/red,blue,green'
#     expected: 'http://demo.org/red,green,blue'
404 Not Found

Trace begun at H:\.cpanm\work\1454921844.1384\Catmandu-1.00_01\blib\lib\Catmandu\Importer.pm line 125
Catmandu::Importer::_build_fh('T::Importer=HASH(0x334404c)') called at (eval 229) line 18
Catmandu::Importer::fh('T::Importer=HASH(0x334404c)') called at t\Catmandu-Importer.t line 71
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 12.
t/Catmandu-Importer.t .................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/12 subtests 
t/Catmandu-Interactive.t ................. ok
t/Catmandu-Iterable.t .................... ok
t/Catmandu-Iterator.t .................... ok
t/Catmandu-MultiIterator.t ............... ok
t/Catmandu-Paged.t ....................... ok
t/Catmandu-Pluggable.t ................... ok
t/Catmandu-Plugin-Datestamps.t ........... ok
t/Catmandu-Plugin-Versioning.t ........... ok
t/Catmandu-Sane.t ........................ ok
t/Catmandu-Searchable.t .................. ok
t/Catmandu-Serializer.t .................. ok
t/Catmandu-Store-Hash.t .................. ok
t/Catmandu-Store-Multi.t ................. ok
t/Catmandu-Store.t ....................... ok

#   Failed test 'join_path'
#   at t/Catmandu-Util.t line 250.
#          got: '\it'
#     expected: '/it'

#   Failed test 'segmented_path'
#   at t/Catmandu-Util.t line 252.
#          got: '\x\12\34\56\78'
#     expected: '/x/12/34/56/78'
# Looks like you failed 2 tests of 572.
t/Catmandu-Util.t ........................ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/572 subtests 
t/Catmandu-Validator-Simple.t ............ ok
t/Catmandu-Validator.t ................... ok

#   Failed test 'root'
#   at t/Catmandu.t line 63.
#          got: '\.cpanm\work\1454921844.1384\Catmandu-1.00_01\t'
#     expected: 'H:\.cpanm\work\1454921844.1384\Catmandu-1.00_01\t'

#   Failed test 'roots'
#   at t/Catmandu.t line 64.
#     Structures begin differing at:
#          $got->[0] = '\.cpanm\work\1454921844.1384\Catmandu-1.00_01\t'
#     $expected->[0] = 'H:\.cpanm\work\1454921844.1384\Catmandu-1.00_01\t'
# Looks like you failed 2 tests of 28.
t/Catmandu.t ............................. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/28 subtests 
t/author-pod-syntax.t .................... skipped: these tests are for testing by the author

Test Summary Report
-------------------
t/Catmandu-Importer.t                  (Wstat: 65280 Tests: 12 Failed: 1)
  Failed test:  12
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/Catmandu-Util.t                      (Wstat: 512 Tests: 572 Failed: 2)
  Failed tests:  487, 489
  Non-zero exit status: 2
t/Catmandu.t                           (Wstat: 512 Tests: 28 Failed: 2)
  Failed tests:  24-25
  Non-zero exit status: 2
Files=139, Tests=1733, 614 wallclock secs ( 0.83 usr +  0.61 sys =  1.43 CPU)
Result: FAIL
Failed 3/139 test programs. 5/1733 subtests failed.
-> FAIL Installing Catmandu failed. See H:\.cpanm\work\1454921844.1384\build.log for details. Retry with --force to force install it.
```

**Comment by nics** [comment]
This is fixed in f6f9ed463bd4a7be72b9f447b403555222a09906 (release 1.00_02)

**Comment by jorol** [comment]
Install still fails:
```terminal 
$ cpanm --dev Catmandu
--> Working on Catmandu
Fetching http://cpan.metacpan.org/authors/id/N/NI/NICS/Catmandu-1.00_02.tar.gz ... OK
Configuring Catmandu-1.00_02 ... OK
==> Found dependencies: URI::Template
--> Working on URI::Template
Fetching http://www.cpan.org/authors/id/B/BR/BRICAS/URI-Template-0.22.tar.gz ... OK
Configuring URI-Template-0.22 ... OK
Building and testing URI-Template-0.22 ... OK
Successfully installed URI-Template-0.22 (upgraded from 0.18)
Building and testing Catmandu-1.00_02 ... FAIL
! Installing Catmandu failed. See H:\.cpanm\work\1455010161.6100\build.log for details. Retry with --force to force install it.
1 distribution installed
$ less H:\.cpanm\work\1455010161.6100\build.log
...
#   Failed test 'join_path'
#   at t/Catmandu-Util.t line 250.
#          got: '\it'
#     expected: '/it'

#   Failed test 'segmented_path'
#   at t/Catmandu-Util.t line 252.
#          got: '\x\12\34\56\78'
#     expected: '/x/12/34/56/78'
# Looks like you failed 2 tests of 572.
t/Catmandu-Util.t ........................ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/572 subtests 
t/Catmandu-Validator-Simple.t ............ ok
t/Catmandu-Validator.t ................... ok

#   Failed test 'root'
#   at t/Catmandu.t line 63.
#          got: '\.cpanm\work\1455010161.6100\Catmandu-1.00_02\t'
#     expected: 'H:\.cpanm\work\1455010161.6100\Catmandu-1.00_02\t'

#   Failed test 'roots'
#   at t/Catmandu.t line 64.
#     Structures begin differing at:
#          $got->[0] = '\.cpanm\work\1455010161.6100\Catmandu-1.00_02\t'
#     $expected->[0] = 'H:\.cpanm\work\1455010161.6100\Catmandu-1.00_02\t'
# Looks like you failed 2 tests of 28.
t/Catmandu.t ............................. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/28 subtests 
t/author-pod-syntax.t .................... skipped: these tests are for testing by the author

Test Summary Report
-------------------
t/Catmandu-Util.t                      (Wstat: 512 Tests: 572 Failed: 2)
  Failed tests:  487, 489
  Non-zero exit status: 2
t/Catmandu.t                           (Wstat: 512 Tests: 28 Failed: 2)
  Failed tests:  24-25
  Non-zero exit status: 2
Files=139, Tests=1742, 629 wallclock secs ( 0.84 usr +  0.89 sys =  1.73 CPU)
Result: FAIL
Failed 2/139 test programs. 4/1742 subtests failed.
-> FAIL Installing Catmandu failed. See H:\.cpanm\work\1455010161.6100\build.log for details. Retry with --force to force install it.
1 distribution installed

**Comment by nics** [comment]
Hi Johann,

i just made the tests in the dev branch a bit more os-independent, could you please run the tests on windows?

Greets,
nic

**Comment by jorol** [comment]
Down to one error:

```terminal
...
#   Failed test 'normalize_path'
#   at t/Catmandu-Util.t line 253.
#          got: '/it'
#     expected: '\it'
# Looks like you failed 1 test of 572.
t/Catmandu-Util.t ........................ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/572 subtests 
...
Test Summary Report
-------------------
t/Catmandu-Util.t                      (Wstat: 256 Tests: 572 Failed: 1)
  Failed test:  488
  Non-zero exit status: 1
Files=139, Tests=1743, 606 wallclock secs ( 0.90 usr +  0.86 sys =  1.76 CPU)
Result: FAIL
Failed 1/139 test programs. 1/1743 subtests failed.
```

Grüße,

Johann

**Comment by nics** [comment]
Hi Johann, would you mind testing again?

**Comment by jorol** [comment]
After the last commit ccaab5aa3c65b3866dfe2e01906b9a29d3c2185d install on Windows works fine!

Thanks

**Comment by nics** [comment]
cool, i’ll make a new developer release
